hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

# You should add something here. Some common eureka-client options, right? Eureka runs on localhost:8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/